substitutions:
  name: bedroom-ac

esphome:
  name: ${name}
  friendly_name: ${name}

esp8266:
  board: nodemcuv2

# Enable Home Assistant API
api:
  encryption:
    key: !secret bedroom_ac_api_encrpt

ota:
  password: !secret bedroom_ac_ota_pass

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bedroom-Ac Fallback Hotspot"
    password: !secret hot_pass

captive_portal:

# Enable logging
logger:
  # ESP8266 only - disable serial port logging, as the HeatPump component
  # needs the sole hardware UART on the ESP8266
  baud_rate: 0
  level: INFO

# Enable Web server.
web_server:
  port: 80

# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time

# Text sensors with general information.
text_sensor:
  # Expose ESPHome version as sensor.
  - platform: version
    name: ${name} ESPHome Version
  # Expose WiFi information as sensors.
  - platform: wifi_info
    ip_address:
      name: ${name} IP
    ssid:
      name: ${name} SSID
    bssid:
      name: ${name} BSSID

# Sensors with general information.
sensor:
  # Uptime sensor.
  - platform: uptime
    name: ${name} Uptime

  # WiFi Signal sensor.
  - platform: wifi_signal
    name: ${name} WiFi Signal
    update_interval: 60s

external_components:
    # Adds support to log sent and recieved packages @b1938e1
  - source: github://geoffdavis/esphome-mitsubishiheatpump@develop

climate:
  - platform: mitsubishi_heatpump
    setup_priority: -100  # Woun't work without this
    name: ${name}
    supports:
      mode: [COOL, HEAT, FAN_ONLY, "OFF"]
      fan_mode: [AUTO, LOW, MEDIUM, HIGH]
      swing_mode: ["OFF", VERTICAL]
    visual:
      min_temperature: 10
      max_temperature: 31
      temperature_step: 1.0
